services:
    php:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
    vite:
        image: node:20.16
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "5174:5174"
        command: npm run dev
        depends_on:
            - php
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
    adminer:
        image: adminer
        ports:
            - 9090:8080
        depends_on:
        - db
    db:
         image: postgres:16
         ports:
             - 5442:5432
         volumes:
             - './data:/var/lib/postgresql/data'
         environment:
             - POSTGRES_USER=perinedbase
             - POSTGRES_PASSWORD=perinedbase
             - POSTGRES_DB=perinedbase
